spring.application.name=fx-deals-warehouse

#server.port=8080

# Datasource PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.fxdealswarehouse=DEBUG


